---
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes
  tags: apache

- name: Copy homepage using Jinja2 template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes
  tags: apache

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes
  tags: apache

